name: weather_wizard
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  quiver: ^3.2.1
  http: ^1.2.1
  geolocator: ^11.0.0
  flutter_svg: ^2.0.10+1
  animated_text_kit: ^4.2.2
  flutter_bloc: ^8.1.5
  animated_background: ^2.0.0
  shared_preferences: ^2.2.2
  flutter_gemini: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  test: ^1.24.9
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  mocktail: ^1.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/oldman-all.gif
    - assets/images/pixel_status_bright_sun.png
    - assets/images/pixel_status_rain.png
    - assets/images/pixel_status_cloudy.png
    - assets/images/pixel_status_thunder.png
    - assets/images/pixel_status_windy.png
    - assets/images/pixel_status_snow.png
    - assets/images/pixel_card.png
    - assets/images/pixel_card_white.png
    - assets/images/weather_clearskies_animated.gif
    - assets/images/weather_clearskies_night_animated.gif
    - assets/images/weather_clearskies_animated.gif
    - assets/images/weather_foggy_animated.gif
    - assets/images/weather_portal.gif
    - assets/images/weather_snowy_day.gif
    - assets/images/weather_storm.gif
    - assets/images/quiet_flame.gif
    - assets/images/dungeon_view.gif
    - assets/images/steel_wall.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
  - family: slkscr
    fonts:
      - asset: fonts/slkscr/slkscr.ttf
      - asset: fonts/slkscr/slkscrb.ttf
        weight: 700
      - asset: fonts/slkscr/slkscre.ttf
        style: italic
      - asset: fonts/slkscr/slkscreb.ttf
        style: italic
        weight: 700
  - family: pixelfysans
    fonts:
      - asset: fonts/pixelfysans/PixelifySans-Regular.ttf
        weight: 400
      - asset: fonts/pixelfysans/PixelifySans-Medium.ttf
        weight: 500
      - asset: fonts/pixelfysans/PixelifySans-SemiBold.ttf
        weight: 600
      - asset: fonts/pixelfysans/PixelifySans-Bold.ttf
        weight: 700
  - family: crang
    fonts:
      - asset: fonts/crang/crang.ttf
  - family: dpcomic
    fonts:
      - asset: fonts/dpcomic/dpcomic.ttf
  - family: ponde
    fonts:
      - asset: fonts/ponde/ponde.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
